[Qibo 0.2.11|INFO|2024-09-18 08:57:29]: Loading platform dummy
Traceback (most recent call last):
  File "/nfs/tools/qibo/bin/qq", line 8, in <module>
    sys.exit(command())
  File "/nfs/tools/qibo/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/tools/qibo/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/qibocal/cli/_base.py", line 68, in auto
    runcard = Runcard.load(yaml.safe_load(runcard.read_text(encoding="utf-8")))
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/nfs/tools/qibo/lib/python3.10/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 1, column 1:
    platform: qw11q
    ^
expected <block end>, but found '<block sequence start>'
  in "<unicode string>", line 30, column 2:
     - id: qubit spectroscopy 01
     ^
